### ISSUE TITLE
Getting weird error (false positive)

### ISSUE THREAD

**Issue by SimenB** [webpack-contrib/istanbul-instrumenter-loader#9] opened 2015-05-10 20:53 UTC
`ERROR in Entry module not found: Error: Cannot resolve module 'istanbul-instrumenter' in /Users/simen/Development/experiments/src/assets/`

The weird thing is it obviously works, as I do get coverage report out of it.

`coverage` as reporter, and added the `postLoaders` from the readme.

It doesn't fail, so there's no real issue, but it's annoying getting the warning

**Comment by deepsweet** [comment] 2015-05-11 01:06
can you please try full name `istanbul-instrumenter-loader`? looks like a strange webpack internal error...

**Comment by SimenB** [comment] 2015-05-11 01:08
No difference with full name

**Comment by deepsweet** [comment] 2015-05-11 01:09
`npm ls istanbul-instrumenter-loader`?

**Comment by SimenB** [comment] 2015-05-11 01:11
```
experiment@0.0.0 /Users/simen/Development/experiment
└── istanbul-instrumenter-loader@0.1.2
```

**Comment by deepsweet** [comment] 2015-05-11 02:45
I don't have any project with `istanbul-instrumenter-loader` right now.. can you try it with `npm i webpack@1.8`?

**Comment by SimenB** [comment] 2015-05-11 05:43
Didn't help :cry:

**Comment by deepsweet** [comment] 2015-05-11 05:46
I don't understand how it works at all with this kind of error

**Comment by SimenB** [comment] 2015-05-11 06:19
I know, that's the weird thing :laughing:

**Comment by nicolasantryhoot** [comment] 2015-07-06 17:18
@SimenB Have you had any luck with this? I'm encountering the same error.

**Comment by deepsweet** [comment] 2015-07-07 00:59
can you provide an example repo so I can try to reproduce and fix it?

**Comment by deepsweet** [comment] 2015-08-22 06:06
hi.

did you somehow resolved this problem?

**Comment by SimenB** [comment] 2015-08-22 06:10
We have migrated to ES2015, so we're using `isparta-loader` now. But the warning was thrown until migration. `isparta` does display the same eror

**Comment by deepsweet** [comment] 2015-08-22 06:12
:cry:

**Comment by SimenB** [comment] 2015-08-22 06:30
Oh sorry, that was supposed to say 
> does _not_ display same error
So no problem with `isparta`.

**Comment by nicolasantryhoot** [comment] 2015-11-26 19:00
@deepsweet Just FYI I've since been able to fix this error by using the resolveLoader in my webpack config.

**Comment by deepsweet** [comment] 2017-03-09 16:36
https://github.com/deepsweet/istanbul-instrumenter-loader/issues/48

**Comment by mattlewis92** [comment] 2017-07-10 20:12
I'm going to close this as there's been no reply for over 2 years, I'm hoping that with 2 major versions of webpack later, whatever the issue was has gone away by itself 😄

**Closed by mattlewis92** 2017-07-10 20:12 UTC
